name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: "epro.epfforce.systems"
        username: root
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /srv/Eppyforce
          ./rnr.sh
